# Generated by Django 3.1 on 2020-09-04 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('media', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('class_played', models.CharField(choices=[('Chaman', 'Chaman'), ('Chasseur', 'Chasseur'), ('Démoniste', 'Démoniste'), ('Druide', 'Druide'), ('Guerrier', 'Guerrier'), ('Mage', 'Mage'), ('Prêtre', 'Prêtre'), ('Voleur', 'Voleur')], max_length=10, null=True)),
                ('grade', models.CharField(choices=[('Guild Master', 'Guild Master'), ('Officier', 'Officier'), ('Member', 'Member'), ('Pick Up', 'Pick Up')], max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.item')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_council', models.BooleanField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.item')),
            ],
        ),
        migrations.CreateModel(
            name='Attrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(null=True)),
                ('items', models.ManyToManyField(to='accounts.Item')),
                ('members', models.ManyToManyField(to='accounts.Member')),
            ],
        ),
    ]
