# Generated by Django 3.1 on 2020-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='class_played',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
