# Generated by Django 3.1 on 2020-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_class_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='class_played',
            field=models.CharField(choices=[('Chaman', 'Chaman'), ('Chasseur', 'Chasseur'), ('Démoniste', 'Démoniste'), ('Druide', 'Druide'), ('Guerrier', 'Guerrier'), ('Mage', 'Mage'), ('Prêtre', 'Prêtre'), ('Voleur', 'Voleur')], max_length=10, null=True),
        ),
    ]
