# Generated by Django 3.1 on 2020-09-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attrib_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrib',
            name='members',
        ),
        migrations.AddField(
            model_name='attrib',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member'),
        ),
    ]
