# Generated by Django 3.1 on 2020-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200831_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='media',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
